[package]
name = "vba-blocks"
version = "0.0.0"
authors = ["Tim Hall <tim.hall.engr@gmail.com> (https://github.com/timhall)"]

[src]
Build = "./src/Build.bas"
OfficeApplication = "./src/OfficeApplication.cls"
Output = "./src/Output.bas"

[dependencies]
installer = { path = "VBA-Installer" }
json = "^2"

[[targets]]
type = "xlsm"
path = "targets/xlsm"

# [[targets]]
# type = "xlam"
# path = "targets/xlam"

# [[targets]]
# type = "ppam"
# path = "targets/ppam"

# [[targets]]
# type = "dotm"
# path = "targets/dotm"

# TODO Access and Outlook
