[package]
name = "vba-blocks"
version = "0.0.0"
authors = ["Tim Hall <tim.hall.engr@gmail.com> (https://github.com/timhall)"]

[src]
Build = "./src/Build.bas"
OfficeApplication = "./src/OfficeApplication.cls"
Output = "./src/Output.bas"

[dependencies]
installer = { path = "VBA-Installer" }
json = "^2"

[targets]
xlsm = "targets/xlsm"

# TODO xlam, ppam, dotm, Access, and Outlook
