# Test and build vba-blocks
#
# - [x] src
# - [ ] add-ins (one day)
# - [ ] end-to-end (one day)

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/**/*
    - package.json
    - rollup.config.js
    - tsconfig.json
    - yarn.lock

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    yarn test
    yarn build:dev
  displayName: 'Install, test, and build vba-blocks'
