# Test and build vba-blocks

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    yarn test
    yarn build:dev
  displayName: 'Install, test, and build vba-blocks'
