# Test and build vba-blocks

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - src/**/*
    - package.json
    - rollup.config.js
    - tsconfig.json
    - yarn.lock

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
  displayName: 'Install'

- script: |
    yarn typecheck
  displayName: 'Typecheck'

- script: |
    yarn test
  displayName: 'Test'

- script: |
    yarn build:dev
  displayName: 'Build'
