[package]
name = "bootstrap"
version = "0.0.0"
authors = ["Tim Hall <tim.hall.engr@gmail.com> (https://github.com/timhall)"]
publish = false

[src]
Build = "../src/Build.bas"
OfficeApplication = "../src/OfficeApplication.cls"
Output = "../src/Output.bas"

[dependencies]
installer = { path = "../VBA-Installer" }
json = "^2"

[targets]
xlsm = "targets/xlsm"
