[package]
name = "installer"
version = "0.0.0"
authors = ["Tim Hall <tim.hall.engr@gmail.com>"]

[src]
Installer = "src/Installer.bas"

[dependencies]
filesystem = { path = "../VBA-FileSystem" }

# [references.VBIDE]
# version = "5.3"
# guid = "{0002E157-0000-0000-C000-000000000046}"
