[package]
name = "installer"
version = "0.1.0"
authors = ["Tim Hall <tim.hall.engr@gmail.com>"]

[src]
Installer = "src/Installer.bas"

[dependencies]
filesystem = { path = "../vba-filesystem" }

[references]
VBIDE = { version = "5.3", guid = "{0002E157-0000-0000-C000-000000000046}" }

[dev-src]
Tests = "tests/Tests.bas"
InstallerFixture = "tests/InstallerFixture.cls"

[dev-dependencies]
test = "^2.0.0-beta.5"
